### ISSUE TITLE
Dataset Release Time

### ISSUE THREAD

**Issue by royukira** [ParitoshParmar/Fitness-AQA#1]
Hi, thanks for your great work! Could you please provide a release time of dataset?

**Comment by ParitoshParmar** [comment]
Hi @royukira: Thank you for interest in our work! We have actually already released the dataset. The link is available in the ReadMe file under the Dataset section: https://github.com/ParitoshParmar/Fitness-AQA#fitness-aqa-dataset. Or are you facing some problem there?

**Comment by royukira** [comment]
> 

Thanks for your reply! I have filled the request form last week, but I don't recieve any download link.

**Comment by royukira** [comment]
> Hi @royukira: Thank you for interest in our work! We have actually already released the dataset. The link is available in the ReadMe file under the Dataset section: https://github.com/ParitoshParmar/Fitness-AQA#fitness-aqa-dataset. Or are you facing some problem there?

Thanks for your reply! I have filled the request form last week, but I don't recieve any download link.

**Comment by xudif** [comment]
Hi, I also recently submitted a request, did not receive the download link, can you check it?

**Comment by xudif** [comment]
> 

Hi, I also recently submitted a request, did not receive the download link, can you check it?

**Comment by xudif** [comment]
> Hi @royukira : Got it. Let me look into it and get back to you.

Hi, I also recently submitted a request, did not receive the download link, can you check it? @royukira

**Comment by ParitoshParmar** [comment]
Hi @xudif : Thank you for your interest in our work! Just to confirm, we have received your request for the dataset. 

Hi @royukira and @xudif : we thought it might be better to maintain the privacy of the subjects in the videos, so we are taking steps towards that. We will soon send you the links to the processed data. Thank you for your interest and patience!

**Comment by ParitoshParmar** [comment]
@royukira, @xudif: Solved. Please feel free to reopen if you are still facing any issues.
